# Generated by Django 4.2.17 on 2025-01-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customtablerevhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customtablerevhistory',
            options={'verbose_name': 'Table Revision History', 'verbose_name_plural': 'Table Revision Histories'},
        ),
    ]
