# Generated by Django 4.2.17 on 2025-01-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_associated_traffic_by_network_element_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtablerevhistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='customtablerevhistory',
            name='table',
        ),
        migrations.DeleteModel(
            name='customTable',
        ),
        migrations.DeleteModel(
            name='customTableRevHistory',
        ),
    ]
